grpc:
  server:
    port: 3000
    address: 0.0.0.0
  security:
    enabled: true
    key-store-type: JKS
    key-store: classpath:server.jks
    key-store-password: rll8r37zo66644
    key-alias: zsite.asia